# Generated by Django 5.0.4 on 2024-05-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marmut_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
